quarkus:
  datasource:
    db-kind: postgresql
    username: philanidlamini
    password: password123
    jdbc:
      url: jdbc:postgresql://localhost:5432/philanidlamini
  hibernate-orm:
    generate-ddl: false
    packages:
      - za.co.serengti.receipts.entity
      - za.co.serengti.customers.entity
    log:
      sql: true



