quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password:
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: update
      default-schema: public
    log:
      sql: true
    packages:
      - za.co.serengti.receipts.entity
      - za.co.serengti.customers.entity
      - za.co.serengti.merchants.entity
